### ISSUE TITLE
Are you interested in footnotes for this edition? 

### ISSUE THREAD

**Issue by JonathanReeve** [CliffordAnderson/corpus-baudelaire#94]
I think it'd be fun to add Walter Benjamin's notes from _The Arcades Project_ (Convolutes J) that reference _Les Fleurs du Mal_. 

My personal philosophy with TEI editions is, put _everything_ in, and let the XSL sort it out later, i.e. show/hide metatextual elements, but I can see how you might want to keep secondary sources like this out.

**Comment by CliffordAnderson** [comment]
Thanks for the suggestion. It's probably best to have the discussion at the Heard Library repository so I'm closing this issue here. Thanks!

**Comment by JonathanReeve** [comment]
Good point. Opened this issue there.
